const whiteList = [
    'player',
    'carousel-inner',
    'carousel',
    'carousel-item',
    'carousel-control-prev-icon',
    'sr-only',
    'carousel-control-next-icon',
    'carousel-item-right',
    'carousel-item-prev',
    'carousel-item-next',
    'carousel-item-left',
    'btn',
    'accordion',
    'card',
    'card-header',
    'collapse',
    'collapsing',
    'show',
    'card-body',
    'btn-light',
    'spinner-border',
    'spinner-border-sm',
    'swiper-wrapper',
    'swiper-container',
    'swiper-container-initialized',
    'swiper-container-horizontal',
    'swiper-container-pointer-events',
    'swiper-slide',
    'swiper-slide-active',
    'swiper-slide-next',
    'swiper-button-prev',
    'swiper-button-disabled',
    'swiper-button-next'
]

module.exports = { whiteList }